### ISSUE TITLE
[Bug] ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Halimao** [FuelLabs/docs-hub#132]
### env
```shell
$ npm --version
10.2.4

$ pnpm --version
8.11.0

node --version
v21.3.0
```

### Reproduce:
1. run `pnpm install`
2. run `pnpm dev`
3. everything is good, except opening http://127.0.0.1:3000 in browser, shows error

```shell
 ⨯ ReferenceError: document is not defined
    at /home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:302:21
    at /home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:311:5
    at /home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:2:83
    at Object.<anonymous> (/home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.call (node:internal/modules/cjs/loader:1235:19)
    at Module.mod.require (/home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/next@13.5.6_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/require-hook.ts:69:26)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr-react@5.3.0_plyr@3.7.8_react@18.2.0/node_modules/plyr-react/index.js:6:14)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  page: '/'
}
 ✓ Compiled /_error in 338ms (3184 modules)
```

### Content in the browser:

![image](https://github.com/FuelLabs/docs-hub/assets/25278203/214f82fe-d7bd-4c85-81ad-1762e8180757)

full log:
```shell
Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js (302:21)
<unknown>
file:///home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js (311:5)
<unknown>
file:///home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js (2:83)
Object.<anonymous>
file:///home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js (5:3)
Module._compile
node:internal/modules/cjs/loader (1376:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1435:10)
Module.load
node:internal/modules/cjs/loader (1207:32)
Function.Module._load
node:internal/modules/cjs/loader (1023:12)
Module.call
node:internal/modules/cjs/loader (1235:19)
Module.mod.require
file:///home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/next@13.5.6_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/require-hook.ts (69:26)
require
node:internal/modules/helpers (176:18)
Object.<anonymous>
file:///home/halimao/Documents/Workspace/js/github.com/Halimao/docs-hub/node_modules/.pnpm/plyr-react@5.3.0_plyr@3.7.8_react@18.2.0/node_modules/plyr-react/index.js (6:14)
Module._compile
node:internal/modules/cjs/loader (1376:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1435:10)
Module.load
node:internal/modules/cjs/loader (1207:32)
```

**Comment by sarahschwartz** [comment]
It looks like you needed to clone the submodules, I'm unable to reproduce.

**Comment by Halimao** [comment]
> It looks like you needed to clone the submodules, I'm unable to reproduce.

Did you test it in a new machine? I did clone the submodules.

Btw, please close issues after receiving author confirmation, this is the second time you close my issue without my confirmation🙃
